= Shune Lei Yee Tun - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Pocket Project

---

== Overview

My team was given the task to enhance or morph a basic command line interface Addressbook for our software engineering Project. Our team decided to morph the AddressBook into a project management tool named Pocket Project. Pocket Project is designed to suit the needs of software engineering managers by enabling them to store all the information that are essential to project planning such as employees, projects, milestones and tasks so as to make planning projects easier and more convenient for them.

My primary role was to implement the `find` command which is essential in allowing users to navigate through the application. The following sections implementation done in details and also the other contributions and relevant sections I have recorded in the user guide and developer guide.

== Summary of contributions

This section shows a summary of contributions I have made for the project.

* *Major enhancement*: I added the ability to search for projects and employees in the application.
** What it does: The `find` command allows the user to search for projects and employees in the application by using keywords such as `name`, `skill`, or any matching words.
** Justification: Since the application contain so much information, it is difficult for the user to look through the whole list of employees or projects just to look for a certain project/employee. Hence this find command provide a convenient and fast way for the user to extract out the information needed.
** Highlights: This command can be used together with other commands such as `edit` to filter out the employees or project before proceeding on to edit them. The command also support extension as new methods of finding can be added by using different command keywords.
** Credits: _{mention here if you reused any code/ideas from elsewhere or if a third-party library is heavily used in the feature so that a reader can make a more accurate judgement of how much effort went into the feature}_

* *Minor enhancement*: I also added the ability to update the information inside the project.
** What it does: The `edit` command allow users to edit the project information such as name, client, description and deadline.
** Justification: As the project progresses, there are bound to be changes made to the project information hence it is essential to have an `edit` command to make sure that all the information are up to date.
** Highlights:

* *Code contributed*: _

* *Other contributions*:

** Project management:
*** I managed releses version v1.1 and v1.2
** Enhancements to existing features:
*** Change the behaviour of `edit` to `edit employee` command so that it will automatically update the employee in the project as well (pull request #118)
*** Design the UI for the employee summary panel (pull request #155)
** Documentation:
*** Update the diagrams in DG to fit the latest version of the application (pull requests #147)
** Community:
** Tools:
*** Set up reposense

_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=find]
include::../UserGuide.adoc[tag=edit]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=find]


== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
